### ISSUE TITLE
AttributeError: dlsym(0x7ffb00c3faf0, init_fply): symbol not found

### ISSUE THREAD

**Issue by cyshi** [tzwenn/PyOpenAirMirror#13]
Run `> python main.py`

`AttributeError: dlsym(0x7ffb00c3faf0, init_fply): symbol not found`

What should I do?

**Comment by tzwenn** [comment]
Help me reproduce:

* Python version?
* OS version?
* Have you got the dylib?
* What is the callstack?

**Comment by cyshi** [comment]
* python version `2.7.12`
* os version `macOS Sierra 10.12.2; Darwin B000000093944 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64`
* I've got the dylib `MD5 (fply.dylib) = 9831e5c61ed5f8f0db1495a73a1ea785`
* Wenn I run `python main.py`, there is nothing on screen. Then I try to mirror my iphone4s to the server, ouput as follows.   
```
----------------------------------------
Exception happened during processing of request from ('192.168.2.4', 51151)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 650, in __init__
    self.setup()
  File "/Users/shichengyi/project/PyOpenAirMirror/tunes/service.py", line 11, in setup
    common.AirPlayHandler.FPLYHandler.setup(self)
  File "/Users/shichengyi/project/PyOpenAirMirror/common/AirPlayHandler.py", line 78, in setup
    self.fply = fply.FPLY()
  File "/Users/shichengyi/project/PyOpenAirMirror/fply/dylib.py", line 11, in __init__
    self.lib.init_fply.restype = ctypes.c_void_p
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7fe2ec4e2470, init_fply): symbol not found
----------------------------------------
Exception AttributeError: 'dlsym(0x7fe2ec4e2470, uninit_fply): symbol not found' in <bound method FPLY.__del__ of <fply.dylib.FPLY object at 0x10b903250>> ignored
```
Run `nm fply.dylib`
```
                 U ___bzero
                 U ___stack_chk_fail
                 U ___stack_chk_guard
0000000000362570 T _decrypt
                 U _gettimeofday
00000000003625a0 T _init
                 U _memcpy
                 U _memmove
                 U _memset
0000000000362590 T _phase1
0000000000362580 T _phase2
                 U _pthread_cond_init
                 U _pthread_cond_signal
                 U _pthread_cond_wait
                 U _pthread_create
                 U _pthread_mutex_init
                 U _pthread_mutex_lock
                 U _pthread_mutex_unlock
                 U _rand
                 U _sleep
                 U _srand
                 U _time
0000000000006640 t _v1018
0000000000294060 T _v1060
000000000010e550 T _v1068
0000000000448c98 b _v1072.b
000000000062b900 b _v1225
000000000020f770 T _v1247
0000000000448af0 S _v1258
0000000000361970 T _v1263
0000000000448af8 S _v1273
0000000000448b00 S _v1276
0000000000448b08 S _v1291
0000000000448b0c S _v1293
0000000000448b10 S _v130
0000000000361e20 T _v1327
00000000002fca90 T _v1369
0000000000006120 t _v1371
00000000002521d0 T _v1378
0000000000448b20 S _v1454
0000000000253b80 T _v1489
00000000002eef80 T _v1506
0000000000361cf0 T _v154
00000000001af330 T _v1565
000000000013acb0 T _v1566
0000000000448b30 S _v1628
0000000000448b38 S _v1630
0000000000448b40 S _v1633
0000000000252780 T _v1812
0000000000361d10 T _v1836
0000000000361c90 T _v1852
000000000012fb30 T _v1868
0000000000448b48 S _v1874
00000000002fccb0 T _v1879
0000000000109500 T _v191
0000000000114c10 T _v1959
0000000000448b50 S _v2036
0000000000448b58 S _v2037
0000000000448b60 S _v2041
0000000000255c40 T _v2055
0000000000448b68 S _v2060
0000000000448b70 S _v2080
0000000000003630 T _v2174
00000000000085c0 T _v2177
0000000000448b78 S _v219
0000000000448b80 S _v220
0000000000448b88 S _v221
00000000001f66a0 T _v2222
0000000000448b90 S _v223
00000000001f8dc0 T _v2278
0000000000448b98 S _v2323
00000000002fd030 T _v2440
00000000001ea220 T _v2461
00000000001e8bc0 T _v2495
0000000000136070 T _v2554
00000000001b9e00 T _v2641
00000000002fce40 T _v2668
0000000000361cd0 T _v2671
0000000000190750 T _v2750
0000000000188f20 T _v2755
0000000000448b9c S _v28
0000000000448ca0 b _v2869
0000000000251bf0 T _v2873
0000000000448ba0 S _v2926
00000000000061e0 t _v2927
0000000000000f40 T _v2933
0000000000448ba8 S _v2958
00000000001e72d0 T _v2972
0000000000448bb0 S _v3007
000000000015b120 T _v3014
0000000000361f50 T _v3027
00000000002fc8b0 T _v3098
0000000000230b30 T _v3100
0000000000117940 T _v3141
0000000000361450 T _v3169
00000000002fcb30 T _v3172
00000000002102b0 T _v3223
0000000000448bb8 S _v327
0000000000197be0 T _v3291
000000000012a9e0 T _v3292
0000000000007060 T _v3318
0000000000448bbc S _v3376
0000000000448bc0 S _v3377
0000000000448bc4 S _v3380
0000000000361f80 T _v3477
00000000003622c0 T _v3478
00000000002623b0 T _v3482
00000000001a3850 T _v3505
000000000018aca0 T _v3516
0000000000448bc8 S _v3520
0000000000257700 T _v3588
0000000000448bd0 S _v3634
0000000000448bd8 S _v3686
00000000001283f0 T _v3767
0000000000448ac4 D _v38
00000000000f3e60 T _v3818
0000000000155710 T _v3828
0000000000448be0 S _v3843
0000000000161b40 T _v3854
00000000001bb920 T _v3859
0000000000251630 T _v3878
0000000000164b10 T _v3912
0000000000135890 T _v3919
0000000000361fe0 T _v3986
0000000000194150 T _v403
0000000000448be8 S _v4046
00000000003620c0 T _v4097
0000000000448bec S _v4109
0000000000448bf0 S _v4189
00000000002e4bc0 T _v423
0000000000361d90 T _v4239
0000000000200e30 T _v4246
00000000000fc880 T _v4321
0000000000362090 T _v4333
00000000003614f0 T _v4347
000000000012c740 T _v4373
00000000001136c0 T _v4384
000000000062b908 b _v4404.b
0000000000361c30 T _v442
0000000000120b40 T _v4434
0000000000361eb0 T _v4451
0000000000151f70 T _v4463
0000000000361d30 T _v4475
00000000002630c0 T _v4635
0000000000145660 T _v4645
00000000001f0c90 T _v4654
0000000000361d00 T _v4749
0000000000361d20 T _v478
00000000003621c0 T _v4822
00000000002fcf00 T _v4831
00000000003650a0 d _v4846
0000000000448bf8 S _v487
000000000014e770 T _v4923
0000000000361ad0 T _v4941
00000000001ec080 T _v522
0000000000448c00 S _v5223
000000000025bdd0 T _v5242
0000000000448a40 D _v5336
00000000000fa9f0 T _v5350
00000000003613a0 T _v5353
0000000000194820 T _v542
0000000000006930 T _v5421
0000000000006830 T _v5424
0000000000361fb0 T _v5451
0000000000361ce0 T _v5493
0000000000448c08 S _v5495
0000000000448c10 S _v5507
00000000001b3ed0 T _v5508
0000000000448c18 S _v5528
0000000000448c1c S _v5532
0000000000362010 T _v5560
00000000001bae00 T _v5600
0000000000361ed0 T _v5605
000000000026f9a0 T _v5609
0000000000200a20 T _v5616
0000000000448c20 S _v5660
000000000020a290 T _v5665
0000000000448c24 S _v5689
0000000000171390 T _v5707
0000000000448c80 b _v5752.b
00000000001426f0 T _v5755
00000000003650e0 D _v5763
0000000000448c90 b _v5798
0000000000188960 T _v5811
0000000000448c28 S _v5827
0000000000361630 T _v5878
00000000002e36d0 T _v5892
00000000002645b0 T _v5917
0000000000362040 T _v5936
00000000002eeb00 T _v5956
00000000002fcd80 T _v5960
0000000000165120 T _v5984
0000000000361ef0 T _v60
0000000000361860 T _v6118
0000000000361b40 T _v6269
00000000002fc9f0 T _v6288
00000000001a33d0 T _v6353
0000000000361c60 T _v6373
0000000000361e10 T _v6391
00000000001bbf30 T _v6417
0000000000006790 T _v6496
0000000000448ca8 b _v6502.b
0000000000361590 T _v653
0000000000006a30 T _v6563
0000000000361e40 T _v6647
00000000002535c0 T _v6772
0000000000448c88 b _v6787
0000000000007ce0 T _v6812
0000000000448c30 S _v6826
00000000001990d0 T _v6907
0000000000362060 T _v6936
000000000011ddf0 T _v6979
00000000002fc810 T _v7
0000000000448c38 S _v7015
0000000000448c40 S _v7020
0000000000448c44 S _v7025
000000000012a660 T _v7109
00000000002fc950 T _v7111
0000000000361e60 T _v7192
0000000000448c48 S _v72
0000000000448c50 S _v7254
0000000000448c58 S _v7298
0000000000448c5c S _v7300
0000000000121020 T _v7368
00000000002fcbf0 T _v7402
0000000000147110 T _v7410
00000000001963e0 T _v761
0000000000006ac0 T _v811
0000000000448ad0 S _v825
0000000000448ae0 S _v826
0000000000147720 T _v833
0000000000448c60 S _v873
0000000000448c68 S _v874
0000000000448c70 S _v878
0000000000361c00 T _v885
0000000000448c78 S _v9014
0000000000361de0 T _v9027
0000000000448ce0 b _v9029
0000000000448cc0 b _v9030
0000000000294490 T _v908
                 U dyld_stub_binder
```

Thanks @tzwenn.

**Comment by cyshi** [comment]
Now, it works fine on ios10. Thanks.
